project:
  type: website
  output-dir: docs

website:
  title: "Mauricio M. Tejada"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - cv.qmd
      - research.qmd
      - teaching.qmd
      - blog.qmd

resources:
  - CNAME
  - pdf/draft_tejada_commuting.pdf
  - pdf/draft_tejada_hours.pdf
  - pdf/draft_tejada_savings.pdf
  - pdf/draft_tejada_minimum_wage.pdf
 
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true